# Nixpacks configuration for Railway
providers = ["node"]

[phases.build]
cmds = [
    "npm ci",
    "npx prisma generate"
]

[phases.start]
cmd = "node src/index.js"

[variables]
NODE_ENV = "production"