[build]
builder = "NIXPACKS"

[build.buildCommand]
# Install dependencies and generate Prisma client
command = "npm install && npx prisma generate"

[deploy]
startCommand = "node src/index.js"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10